# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 778d728da613a80df8db8d72d3616417024d5daf928b7effc78818a09bb9ad50a3207c70e53bfd16a395344597bdb895634e4ccd76066e8fab0f6947182e61c7

test:
  secret_key_base: cd3b4497ad359726a51b2709d4d7b17e79e3ec11be9a1da4ba537554b959c635386e2f6d88f444c8dd03850745aa9fb55add2ee08b44271143fdc6457b3ec52e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
